import { v4 as uuid } from "uuid";

export const itemsApi = [
  {
    name: "Product 1",
    quantity: 2,
    cost: 41.13,
    color: "blue",
    brand: "Nike",
    size: 36,
    type: "hiking boots",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 2",
    quantity: 3,
    cost: 51.1,
    color: "red",
    brand: "Other",
    size: 36.5,
    type: "running",
    gender: "men",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 3",
    quantity: 4,
    cost: 10.37,
    color: "green",
    brand: "Adidas",
    size: 37.5,
    type: "dress shoes",
    gender: "men",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 4",
    quantity: 3,
    cost: 27.17,
    color: "white",
    brand: "Adidas",
    size: 7,
    type: "running",
    gender: "women",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 5",
    quantity: 7,
    cost: 34.97,
    color: "white",
    brand: "Adidas",
    size: 37.5,
    type: "dress shoes",
    gender: "men",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 6",
    quantity: 8,
    cost: 60.65,
    color: "green",
    brand: "Bitis",
    size: 6,
    type: "running",
    gender: "unisex",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 7",
    quantity: 6,
    cost: 36.81,
    color: "white",
    brand: "Nike",
    size: 36.5,
    type: "sneaker",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 8",
    quantity: 8,
    cost: 9.27,
    color: "green",
    brand: "Other",
    size: 8,
    type: "running",
    gender: "unisex",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 9",
    quantity: 9,
    cost: 96.33,
    color: "green",
    brand: "Other",
    size: 5,
    type: "dress shoes",
    gender: "women",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 10",
    quantity: 7,
    cost: 81.67,
    color: "red",
    brand: "Adidas",
    size: 37.5,
    type: "hiking boots",
    gender: "women",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 11",
    quantity: 10,
    cost: 55.79,
    color: "white",
    brand: "Nike",
    size: 8,
    type: "sneaker",
    gender: "unisex",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 12",
    quantity: 2,
    cost: 40.06,
    color: "white",
    brand: "Other",
    size: 36,
    type: "hiking boots",
    gender: "women",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 13",
    quantity: 9,
    cost: 27.07,
    color: "blue",
    brand: "Bitis",
    size: 6,
    type: "sneaker",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 14",
    quantity: 1,
    cost: 34.9,
    color: "green",
    brand: "Bitis",
    size: 36.5,
    type: "sandal",
    gender: "women",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 15",
    quantity: 1,
    cost: 30.9,
    color: "red",
    brand: "Nike",
    size: 8,
    type: "hiking boots",
    gender: "men",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 16",
    quantity: 10,
    cost: 28.78,
    color: "white",
    brand: "Nike",
    size: 7,
    type: "dress shoes",
    gender: "women",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 17",
    quantity: 4,
    cost: 61.48,
    color: "blue",
    brand: "Nike",
    size: 5,
    type: "sandal",
    gender: "men",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 18",
    quantity: 4,
    cost: 27.47,
    color: "blue",
    brand: "Puma",
    size: 40.5,
    type: "sandal",
    gender: "men",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 19",
    quantity: 7,
    cost: 68.65,
    color: "red",
    brand: "Other",
    size: 7,
    type: "running",
    gender: "women",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 20",
    quantity: 10,
    cost: 31.62,
    color: "green",
    brand: "Other",
    size: 7,
    type: "hiking boots",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 21",
    quantity: 4,
    cost: 49.78,
    color: "red",
    brand: "Adidas",
    size: 6,
    type: "sandal",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 22",
    quantity: 8,
    cost: 68.9,
    color: "blue",
    brand: "Adidas",
    size: 7,
    type: "hiking boots",
    gender: "men",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 23",
    quantity: 8,
    cost: 50.6,
    color: "blue",
    brand: "Other",
    size: 36.5,
    type: "sandal",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 24",
    quantity: 2,
    cost: 29.77,
    color: "green",
    brand: "Bitis",
    size: 37.5,
    type: "sandal",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 25",
    quantity: 1,
    cost: 30.86,
    color: "blue",
    brand: "Nike",
    size: 37.5,
    type: "sneaker",
    gender: "men",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 26",
    quantity: 4,
    cost: 67.63,
    color: "blue",
    brand: "Other",
    size: 9,
    type: "sandal",
    gender: "women",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 27",
    quantity: 10,
    cost: 49.48,
    color: "blue",
    brand: "Other",
    size: 37.5,
    type: "hiking boots",
    gender: "women",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 28",
    quantity: 7,
    cost: 27.61,
    color: "white",
    brand: "Bitis",
    size: 36.5,
    type: "running",
    gender: "women",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 29",
    quantity: 6,
    cost: 72.13,
    color: "red",
    brand: "Adidas",
    size: 7,
    type: "running",
    gender: "men",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 30",
    quantity: 7,
    cost: 1.02,
    color: "green",
    brand: "Nike",
    size: 9,
    type: "sandal",
    gender: "men",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 31",
    quantity: 2,
    cost: 47.85,
    color: "white",
    brand: "Adidas",
    size: 36.5,
    type: "sandal",
    gender: "women",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 32",
    quantity: 8,
    cost: 44.45,
    color: "red",
    brand: "Other",
    size: 8,
    type: "running",
    gender: "women",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 33",
    quantity: 4,
    cost: 59.93,
    color: "white",
    brand: "Nike",
    size: 8,
    type: "sandal",
    gender: "women",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 34",
    quantity: 9,
    cost: 1.01,
    color: "white",
    brand: "Other",
    size: 36,
    type: "dress shoes",
    gender: "unisex",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 35",
    quantity: 7,
    cost: 38.79,
    color: "white",
    brand: "Bitis",
    size: 36.5,
    type: "running",
    gender: "unisex",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 36",
    quantity: 7,
    cost: 24.93,
    color: "white",
    brand: "Nike",
    size: 36.5,
    type: "sandal",
    gender: "men",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 37",
    quantity: 3,
    cost: 0.26,
    color: "blue",
    brand: "Other",
    size: 5,
    type: "dress shoes",
    gender: "men",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 38",
    quantity: 10,
    cost: 77.03,
    color: "white",
    brand: "Puma",
    size: 5,
    type: "dress shoes",
    gender: "women",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 39",
    quantity: 6,
    cost: 56.9,
    color: "red",
    brand: "Other",
    size: 36.5,
    type: "dress shoes",
    gender: "men",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 40",
    quantity: 7,
    cost: 16.31,
    color: "green",
    brand: "Nike",
    size: 36.5,
    type: "sneaker",
    gender: "men",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 41",
    quantity: 1,
    cost: 57.9,
    color: "white",
    brand: "Adidas",
    size: 8,
    type: "sandal",
    gender: "men",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 42",
    quantity: 1,
    cost: 90.36,
    color: "blue",
    brand: "Puma",
    size: 6,
    type: "hiking boots",
    gender: "men",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 43",
    quantity: 4,
    cost: 61.64,
    color: "red",
    brand: "Other",
    size: 7,
    type: "sneaker",
    gender: "women",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 44",
    quantity: 10,
    cost: 25.63,
    color: "blue",
    brand: "Puma",
    size: 9,
    type: "sandal",
    gender: "unisex",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 45",
    quantity: 9,
    cost: 12.72,
    color: "white",
    brand: "Nike",
    size: 40.5,
    type: "dress shoes",
    gender: "men",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 46",
    quantity: 6,
    cost: 89.49,
    color: "white",
    brand: "Nike",
    size: 8,
    type: "running",
    gender: "women",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 47",
    quantity: 8,
    cost: 98.52,
    color: "white",
    brand: "Other",
    size: 36.5,
    type: "running",
    gender: "men",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 48",
    quantity: 6,
    cost: 0.52,
    color: "red",
    brand: "Nike",
    size: 6,
    type: "dress shoes",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 49",
    quantity: 4,
    cost: 20.79,
    color: "blue",
    brand: "Other",
    size: 36,
    type: "sneaker",
    gender: "men",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 50",
    quantity: 6,
    cost: 13.89,
    color: "blue",
    brand: "Adidas",
    size: 36.5,
    type: "hiking boots",
    gender: "women",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 51",
    quantity: 10,
    cost: 5.11,
    color: "red",
    brand: "Bitis",
    size: 5,
    type: "dress shoes",
    gender: "men",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 52",
    quantity: 4,
    cost: 85.03,
    color: "blue",
    brand: "Adidas",
    size: 40.5,
    type: "sandal",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 53",
    quantity: 3,
    cost: 59.13,
    color: "blue",
    brand: "Nike",
    size: 7,
    type: "hiking boots",
    gender: "women",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 54",
    quantity: 3,
    cost: 90.76,
    color: "white",
    brand: "Adidas",
    size: 9,
    type: "running",
    gender: "unisex",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 55",
    quantity: 6,
    cost: 11.94,
    color: "red",
    brand: "Nike",
    size: 40.5,
    type: "hiking boots",
    gender: "men",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 56",
    quantity: 9,
    cost: 75.61,
    color: "green",
    brand: "Bitis",
    size: 9,
    type: "dress shoes",
    gender: "women",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 57",
    quantity: 10,
    cost: 95.24,
    color: "white",
    brand: "Adidas",
    size: 5,
    type: "sneaker",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 58",
    quantity: 4,
    cost: 68.16,
    color: "white",
    brand: "Puma",
    size: 9,
    type: "dress shoes",
    gender: "unisex",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 59",
    quantity: 1,
    cost: 29.66,
    color: "blue",
    brand: "Puma",
    size: 36.5,
    type: "dress shoes",
    gender: "women",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 60",
    quantity: 2,
    cost: 42.46,
    color: "blue",
    brand: "Puma",
    size: 40.5,
    type: "running",
    gender: "unisex",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 61",
    quantity: 10,
    cost: 89.77,
    color: "blue",
    brand: "Nike",
    size: 36.5,
    type: "sneaker",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 62",
    quantity: 9,
    cost: 0.05,
    color: "red",
    brand: "Other",
    size: 36.5,
    type: "hiking boots",
    gender: "men",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 63",
    quantity: 4,
    cost: 55.32,
    color: "green",
    brand: "Puma",
    size: 36.5,
    type: "running",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 64",
    quantity: 9,
    cost: 23.89,
    color: "red",
    brand: "Puma",
    size: 8,
    type: "hiking boots",
    gender: "unisex",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 65",
    quantity: 10,
    cost: 47.93,
    color: "green",
    brand: "Puma",
    size: 9,
    type: "running",
    gender: "unisex",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 66",
    quantity: 6,
    cost: 6.61,
    color: "blue",
    brand: "Bitis",
    size: 36.5,
    type: "dress shoes",
    gender: "unisex",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 67",
    quantity: 1,
    cost: 53.1,
    color: "white",
    brand: "Other",
    size: 36.5,
    type: "hiking boots",
    gender: "unisex",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 68",
    quantity: 3,
    cost: 13.48,
    color: "green",
    brand: "Puma",
    size: 8,
    type: "running",
    gender: "women",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 69",
    quantity: 9,
    cost: 93.89,
    color: "red",
    brand: "Other",
    size: 5,
    type: "hiking boots",
    gender: "men",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 70",
    quantity: 2,
    cost: 18.85,
    color: "white",
    brand: "Puma",
    size: 9,
    type: "dress shoes",
    gender: "unisex",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 71",
    quantity: 9,
    cost: 40.81,
    color: "white",
    brand: "Adidas",
    size: 37.5,
    type: "sneaker",
    gender: "women",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 72",
    quantity: 8,
    cost: 84.83,
    color: "white",
    brand: "Nike",
    size: 37.5,
    type: "sneaker",
    gender: "women",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 73",
    quantity: 1,
    cost: 22.87,
    color: "blue",
    brand: "Puma",
    size: 9,
    type: "sandal",
    gender: "unisex",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 74",
    quantity: 7,
    cost: 32.61,
    color: "blue",
    brand: "Puma",
    size: 6,
    type: "dress shoes",
    gender: "men",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 75",
    quantity: 6,
    cost: 71.78,
    color: "white",
    brand: "Bitis",
    size: 7,
    type: "sneaker",
    gender: "women",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 76",
    quantity: 3,
    cost: 29.66,
    color: "blue",
    brand: "Other",
    size: 6,
    type: "hiking boots",
    gender: "unisex",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 77",
    quantity: 1,
    cost: 53.84,
    color: "green",
    brand: "Puma",
    size: 37.5,
    type: "sandal",
    gender: "women",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 78",
    quantity: 1,
    cost: 29.35,
    color: "red",
    brand: "Puma",
    size: 36,
    type: "sneaker",
    gender: "women",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 79",
    quantity: 8,
    cost: 15.43,
    color: "blue",
    brand: "Other",
    size: 5,
    type: "hiking boots",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 80",
    quantity: 3,
    cost: 56.75,
    color: "red",
    brand: "Puma",
    size: 37.5,
    type: "sneaker",
    gender: "women",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 81",
    quantity: 7,
    cost: 31.38,
    color: "green",
    brand: "Adidas",
    size: 9,
    type: "dress shoes",
    gender: "unisex",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 82",
    quantity: 10,
    cost: 3.73,
    color: "green",
    brand: "Bitis",
    size: 37.5,
    type: "running",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 83",
    quantity: 2,
    cost: 98.51,
    color: "green",
    brand: "Puma",
    size: 37.5,
    type: "sandal",
    gender: "women",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 84",
    quantity: 2,
    cost: 1.91,
    color: "green",
    brand: "Puma",
    size: 36.5,
    type: "sandal",
    gender: "unisex",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 85",
    quantity: 1,
    cost: 23.09,
    color: "green",
    brand: "Nike",
    size: 36.5,
    type: "dress shoes",
    gender: "women",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 86",
    quantity: 7,
    cost: 26.73,
    color: "green",
    brand: "Adidas",
    size: 36.5,
    type: "sandal",
    gender: "women",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 87",
    quantity: 2,
    cost: 72.81,
    color: "blue",
    brand: "Other",
    size: 8,
    type: "dress shoes",
    gender: "unisex",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 88",
    quantity: 4,
    cost: 68.94,
    color: "red",
    brand: "Bitis",
    size: 9,
    type: "running",
    gender: "unisex",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 89",
    quantity: 2,
    cost: 41.95,
    color: "red",
    brand: "Bitis",
    size: 6,
    type: "dress shoes",
    gender: "women",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 90",
    quantity: 2,
    cost: 65.62,
    color: "green",
    brand: "Bitis",
    size: 36.5,
    type: "dress shoes",
    gender: "women",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 91",
    quantity: 1,
    cost: 76.45,
    color: "blue",
    brand: "Nike",
    size: 36.5,
    type: "dress shoes",
    gender: "women",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 92",
    quantity: 1,
    cost: 85.24,
    color: "blue",
    brand: "Adidas",
    size: 40.5,
    type: "sneaker",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 93",
    quantity: 8,
    cost: 11.88,
    color: "red",
    brand: "Puma",
    size: 37.5,
    type: "running",
    gender: "women",
    age: "adult",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 94",
    quantity: 9,
    cost: 9.69,
    color: "red",
    brand: "Puma",
    size: 6,
    type: "dress shoes",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 95",
    quantity: 6,
    cost: 71.13,
    color: "green",
    brand: "Puma",
    size: 5,
    type: "running",
    gender: "unisex",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 96",
    quantity: 2,
    cost: 96.48,
    color: "white",
    brand: "Nike",
    size: 36,
    type: "hiking boots",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 97",
    quantity: 2,
    cost: 23.98,
    color: "blue",
    brand: "Other",
    size: 37.5,
    type: "sandal",
    gender: "women",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 98",
    quantity: 7,
    cost: 69.65,
    color: "blue",
    brand: "Other",
    size: 37.5,
    type: "dress shoes",
    gender: "men",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 99",
    quantity: 4,
    cost: 33.77,
    color: "red",
    brand: "Nike",
    size: 5,
    type: "running",
    gender: "unisex",
    age: "kid",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
  {
    name: "Product 100",
    quantity: 3,
    cost: 5.58,
    color: "red",
    brand: "Adidas",
    size: 9,
    type: "running",
    gender: "unisex",
    age: "teenager",
    add_date: "2023-05-07 12:34:56",
    item_id: uuid(),
  },
];
